# Generated by Django 5.1.2 on 2024-10-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('NGN', 'Nigerian Naira')], default='NGN', max_length=3),
        ),
    ]
